# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Czesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kontrahent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('nip', models.CharField(max_length=255)),
                ('ulica', models.CharField(max_length=255)),
                ('kod', models.CharField(max_length=255)),
                ('miasto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Naprawa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'w trakcie'), ('CLOSED', 'zakonczona')], max_length=255)),
                ('data_rozpoczecia', models.DateField()),
                ('data_zakonczenia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Oddzial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('mpk', models.CharField(max_length=255)),
                ('kontahent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serwis.Kontrahent')),
            ],
        ),
        migrations.CreateModel(
            name='Przeglad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ilosc_czynnika', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dzialajace', models.BinaryField()),
                ('uwagi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypUrzadzenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Urzadzenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producent', models.CharField(max_length=255)),
                ('typ', models.CharField(max_length=255)),
                ('moc', models.DecimalField(decimal_places=1, max_digits=6)),
                ('rodzaj_czynnika', models.CharField(choices=[('R410', 'R 410'), ('R128', 'R 128'), ('R312', 'R 312'), ('R234', 'R 234')], default='R410', max_length=255)),
                ('miejsce_montazu', models.CharField(max_length=255)),
                ('koniec_gwarancji', models.DateField()),
                ('multi', models.BinaryField()),
                ('ile_multi', models.PositiveSmallIntegerField()),
                ('strategiczny', models.BinaryField()),
                ('uwagi', models.TextField()),
                ('numer_seryjny', models.CharField(max_length=255)),
                ('oddzial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serwis.Oddzial')),
                ('typ_urzadzenia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serwis.TypUrzadzenia')),
            ],
        ),
        migrations.CreateModel(
            name='WZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=255)),
                ('ilosc', models.DecimalField(decimal_places=2, max_digits=8)),
                ('czesc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serwis.Czesc')),
            ],
        ),
        migrations.AddField(
            model_name='przeglad',
            name='urzadzenie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serwis.Urzadzenie'),
        ),
    ]
