# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oddzial',
            old_name='kontahent',
            new_name='kontrahent',
        ),
    ]
