# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0002_auto_20160830_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urzadzenie',
            name='multi',
            field=models.IntegerField(choices=[('1', 'TAK'), ('0', 'NIE')]),
        ),
    ]
