# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0004_auto_20160830_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urzadzenie',
            name='ile_multi',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='urzadzenie',
            name='multi',
            field=models.IntegerField(choices=[('TAK', 'TAK'), ('NIE', 'NIE')]),
        ),
        migrations.AlterField(
            model_name='urzadzenie',
            name='strategiczny',
            field=models.IntegerField(choices=[('TAK', 'TAK'), ('NIE', 'NIE')]),
        ),
        migrations.AlterField(
            model_name='urzadzenie',
            name='uwagi',
            field=models.TextField(blank=True),
        ),
    ]
